//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public decimal ID_BOLETA { get; set; }
        public decimal TOTAL_BOLETA { get; set; }
        public System.DateTime FECHA_BOLETA { get; set; }
        public decimal ID_MESA { get; set; }
    
        public virtual MESA MESA { get; set; }
    }
}
