//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMIBLE
    {
        public CONSUMIBLE()
        {
            this.DETA_MENU_CONSU = new HashSet<DETA_MENU_CONSU>();
        }
    
        public decimal ID_CONSUMIBLE { get; set; }
        public string NOMBRE_CONSUMIBLE { get; set; }
        public string DESCRIPCION_CONSUMIBLE { get; set; }
        public decimal STOCK { get; set; }
        public decimal ID_TIPO_CONSUMIBLE { get; set; }
        public decimal ID_BODEGA { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
        public virtual TIPO_CONSUMIBLE TIPO_CONSUMIBLE { get; set; }
        public virtual ICollection<DETA_MENU_CONSU> DETA_MENU_CONSU { get; set; }
    }
}
