//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOPEDIDO
    {
        public ESTADOPEDIDO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal ID_ESTADO { get; set; }
        public string NOMBRE_ESTADO { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
