//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMOS
    {
        public decimal ID_INSUMOS { get; set; }
        public string PEDIDOINSUMO { get; set; }
        public decimal ID_BODEGA { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
    }
}
