//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.DETA_MENU_CONSU = new HashSet<DETA_MENU_CONSU>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal ID_MENU { get; set; }
        public string NOMBRE_MENU { get; set; }
        public string DESCRIPCION_MENU { get; set; }
    
        public virtual ICollection<DETA_MENU_CONSU> DETA_MENU_CONSU { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
