//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.RESERVA = new HashSet<RESERVA>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal ID_MESA { get; set; }
        public string UBICACION_MESA { get; set; }
        public Nullable<decimal> MAX_COMENSALES_MESA { get; set; }
        public string USADO_MESA { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
