//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.RESERVA = new HashSet<RESERVA>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID_PERSONA { get; set; }
        public string RUT_PERSONA { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string APATERNO_PERSONA { get; set; }
        public string AMATERNO_PERSONA { get; set; }
        public Nullable<decimal> TELEFONO_PERSONA { get; set; }
        public string CORREO_PERSONA { get; set; }
        public string ACTIVO_PERSONA { get; set; }
        public decimal ID_CARGO_PERSONA { get; set; }
        public decimal ID_COMUNA_PERSONA { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
