//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public Nullable<System.DateTime> FECHA_RESERVA { get; set; }
        public decimal ID_MESA_RESERVA { get; set; }
        public decimal ID_PERSONA { get; set; }
    
        public virtual MESA MESA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
