//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_siglo_XI.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CONSUMIBLE
    {
        public TIPO_CONSUMIBLE()
        {
            this.CONSUMIBLE = new HashSet<CONSUMIBLE>();
        }
    
        public decimal ID_TIPO_CONSUMIBLE { get; set; }
        public string NOMBRE_TIPO_CONSUMIBLE { get; set; }
    
        public virtual ICollection<CONSUMIBLE> CONSUMIBLE { get; set; }
    }
}
